Fix gis functions
Flexberry/NewPlatform.Flexberry.ORM.GisMSSQLDataService pull request #8
Opened 2021-07-30 07:01 UTC by leoleopon

2021-07-30 08:37 UTC, NicholasNoise requested changes

2021-07-30 08:37 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            if (value != null && value.GetType().IsSubclassOf(typeof(Geography)))
`if (value is Geography geogr)`

2021-07-30 08:37 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            if (value != null && value.GetType().IsSubclassOf(typeof(Geometry)))
+1

2021-07-30 08:37 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            ExternalLangDef langDef = sqlLangDef as ExternalLangDef;
Не используется же

2021-07-30 08:37 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
кмк так универсальнее
```
string part0 = value.Parameters[0] is VariableDef varDef0
  ? PutIdentifierIntoBrackets(varDef0.StringedView)
  : convertValue(value.Parameters[0]);
...
return $"{part0}.{sqlFunction}({part1}){sqlCondition}";
```

2021-07-30 08:37 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            const string GeoDistance = "GeoDistance";
А это же константы из `ExternalLangDef` (от части)

2021-08-02 12:53 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
Поправил.

2021-08-02 12:54 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            ExternalLangDef langDef = sqlLangDef as ExternalLangDef;
Уже используется (в новой реализации).

2021-08-02 12:55 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            const string GeoDistance = "GeoDistance";
Это свойства экземпляра. Реализовал использование.

2021-08-02 12:56 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            if (value != null && value.GetType().IsSubclassOf(typeof(Geometry)))
Унаследованный код. Предложенная замена допустима (хотя и не эквивалентна) - поправил.

2021-08-02 12:57 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            if (value != null && value.GetType().IsSubclassOf(typeof(Geography)))
Унаследованный код. Предложенная замена допустима (хотя и не эквивалентна) - поправил.

2021-08-02 13:16 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
Поправил, но не стильно.

2021-08-02 14:11 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
Да, да - сейчас стильно.

2021-08-02 14:13 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
В C# принято иначе:
```
                sqlParameters[0] = value.Parameters[0] is VariableDef vd0
                    ? PutIdentifierIntoBrackets(vd0.StringedView)
                    : convertValue(value.Parameters[0]);
```

2021-08-02 14:22 UTC, leoleopon commented on NewPlatform.Flexberry.ORM.GisMSSQLDataService/GisMSSQLDataService.cs
> +            {
Поправил.

2021-08-02 16:39 UTC, NicholasNoise approved these changes

2021-08-03 06:21 UTC, bratchikov approved these changes

2021-08-03 06:24 UTC, merged